# -*- coding: utf-8 -*-
"""Neural Network IPS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bSViM-AwiIDn9Tw0akSVj3Ue0tMUeiPT
"""

import pandas as pd
import seaborn as sns
import numpy as np

from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from matplotlib import pyplot

df = pd.read_csv('somedataset.csv')

X = df[['BLE1', 'BLE2', 'BLE3', 'BLE4', 'BLE5', 'BLE6']]
y = df[['PosX', 'PosY']]


X_train, X_test, Y_train, Y_test = train_test_split(
    X, y, test_size=0.3, random_state=101)

model = Sequential()
# add layer ให้โมเดล
# input dimension = 4 เพราะมี 4 feature (BLE1-4)
model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(4, activation='relu'))

model.add(Dense(2, activation='linear'))
# model.add(Dense(2))

model.compile(loss='mse',
              optimizer='rmsprop', metrics=['accuracy'])

model.fit(X_train, Y_train, epochs=50, batch_size=10)

_, accuracy = model.evaluate(X_test, Y_test)
print('Accuracy: %.2f' % (accuracy*100))
